## Linear Regression

In [66]:
from sklearn import linear_model
import pandas as pd
import numpy as np
                    # Load data
data = pd.read_csv("../../Data/wine_quality.csv", sep = ";")
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

#### | Values in the train and test datasets must be numeric and in numpy arrays |

In [67]:
# Train dataset
x_train = data.iloc[:-10:,0:-1]
x_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1584,6.7,0.32,0.44,2.4,0.061,24.0,34.0,0.99484,3.29,0.80,11.6
1585,7.2,0.39,0.44,2.6,0.066,22.0,48.0,0.99494,3.30,0.84,11.5
1586,7.5,0.31,0.41,2.4,0.065,34.0,60.0,0.99492,3.34,0.85,11.4
1587,5.8,0.61,0.11,1.8,0.066,18.0,28.0,0.99483,3.55,0.66,10.9
1588,7.2,0.66,0.33,2.5,0.068,34.0,102.0,0.99414,3.27,0.78,12.8

In [68]:
y_train = data.iloc[:-10:,-1]
y_train

0       5
1       5
2       5
3       6
4       5
       ..
1584    7
1585    6
1586    6
1587    6
1588    6
Name: quality, Length: 1589, dtype: int64

In [69]:
x_test = data.iloc[-10::,0:-1]
x_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1589,6.6,0.725,0.20,7.8,0.073,29.0,79.0,0.99770,3.29,0.54,9.2
1590,6.3,0.550,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6
1591,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6
1592,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [70]:
y_test = data.iloc[-10::,-1]
y_test = np.array(y_test)
y_test

array([5, 6, 6, 6, 6, 5, 6, 6, 5, 6])

In [71]:
linear = linear_model.LinearRegression()
linear.fit(x_train, y_train)
linear.score(x_train, y_train)

print("Coefficient:", linear.coef_)
print("Intercept:", linear.intercept_)

predicted = linear.predict(x_test)
predicted

Coefficient: [ 2.49745540e-02 -1.08399014e+00 -1.82032718e-01  1.63842800e-02
 -1.87180196e+00  4.44643518e-03 -3.27831609e-03 -1.81139463e+01
 -4.15712906e-01  9.14971965e-01  2.76057120e-01]
Intercept: 22.205631829642442

array([5.00311064, 6.20838935, 5.55248402, 5.94405141, 5.49294693,
       5.53137254, 5.96315314, 5.94405141, 5.47181506, 6.00879671])

In [72]:
def check_precision(test, predicted):
    correct = 0
    for i in range(len(test)):
        if round(test[i]) == round(predicted[i]):
            correct += 1
    return (correct/len(test))*100

check_precision(y_test, predicted)

80.0